language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt
script: nosetests machotools

notifications:
  email:
    recipients:
      - davidc@enthought.com
    on_success: change
    on_failure: always
